name: PR Preview
description: ""

inputs:
    token:
        required: true
        description: "GitHub token to use for authentication"

    database_path:
        required: true
        description: "Path to the database file in the Repo"

runs:
    using: node20
    main: dist/main.js
