name: PR Preview
description: "Deploys a preview environment for pull requests using specified credentials and resources."

inputs:
    token:
        description: "GitHub token to use for authentication."
        required: true
    email:
        description: "Email address for authentication."
        required: true
    password:
        description: "Password for authentication."
        required: true
    api_url:
        description: "The API URL for deployment operations."
        required: true
    app_url:
        description: "The application URL for the preview environment."
        required: true
    database_file_id:
        description: "File ID to use as the database."
        required: true
    project_id:
        description: "Project ID for creating resources."
        required: true
    environment_id:
        description: "Environment ID for creating resources."
        required: true
    credential_id:
        description: "Credential ID for creating the application."
        required: true
    server_id:
        description: "Server ID for application deployment."
        required: true
    repository:
        description: "Repository to use for creating the application."
        required: true

runs:
    using: "node20"
    main: "dist/main.js"

branding:
    icon: "cloud"
    color: "blue"
