name: PR Preview
description: ""

inputs:
    github_token:
        required: false
        description: "GitHub token to use for authentication"
        default: ${{ github.token }}

    database_path:
        required: true
        description: "Path to the database file in the Repo"

runs:
    using: composite
    steps:
        - name: Run the Action executable
          run: $GITHUB_ACTION_PATH/dist/main
          shell: sh
