name: PR Preview
description: ""

inputs:
    token:
        required: true
        description: "GitHub token to use for authentication"

    email:
        required: true
        description: "Email address to use for authentication"

    password:
        required: true
        description: "Password to use for authentication"

    api_url:
        required: true
        description: "API URL"

    app_url:
        required: true
        description: "APP URL"

    database_file_id:
        required: true
        description: "File ID to use as database"

    project_id:
        required: true
        description: "Project ID to use for create resources"

    environment_id:
        required: true
        description: "Environment ID to use for create resources"

    credential_id:
        required: true
        description: "Credential ID to use for create application"

    server_id:
        required: true
        description: "Server ID to use for create application"

    repository:
        required: true
        description: "Repository to use for create application"

runs:
    using: node20
    main: dist/main.js
