name: Devopness - Request
description: "Send a request to a Devopness API endpoint"

inputs:
    host:
        required: true
        description: "Host to send the request to"
    path:
        required: true
        description: "URL path to send the request to (relative to the host)"
    method:
        required: true
        description: "HTTP method to use for the request (GET, POST, etc.)"
    token:
        required: false
        description: "Base64-encoded Token to use for authentication"
    data:
        required: false
        default: "{}"
        description: "Data to send with the request (JSON format)"

outputs:
    id:
        value: ${{ steps.request.outputs.request-id }}
        description: "ID of the action (from X-Devopness-Action-Id header)"
    status:
        value: ${{ steps.request.outputs.status }}
        description: "Status code of the response"
    response:
        value: ${{ steps.request.outputs.response }}
        description: "Response from the request"

runs:
    using: composite
    steps:
        - name: Send request
          id: request
          shell: bash
          run: bash .github/actions/devopness-request/step-1.sh
          env:
              HOST: ${{ inputs.host }}
              PATH: ${{ inputs.path }}
              METHOD: ${{ inputs.method }}
              TOKEN: ${{ inputs.token }}
              DATA: ${{ inputs.data }}

        - name: Cleanup temporary files
          if: always()
          shell: bash
          run: rm -f headers.txt response.json
