name: Devopness - Login
description: "Login to Devopness API and store the token for future use."

inputs:
    host:
        required: true
        description: "Host to send the request to"
    email:
        required: true
        description: "Email to be used for login"
    password:
        required: true
        description: "Password to be used for login"

runs:
    using: node20
    main: dist/main.js
