name: Devopness - Application
description: "Manage Application on Devopness"

inputs:
    host:
        required: true
        description: "Host to send the request to"
    token:
        required: true
        description: "Base64-encoded Token to use for authentication"

    # List Operation
    list:
        required: false
        description: "List Applications"
        default: "false"

    list_environment_id:
        required: false
        description: "ID of the environment to list applications for"
        default: ""

    # Get Operation
    get:
        required: false
        description: "Get Application"
        default: "false"

    get_application_id:
        required: false
        description: "ID of the application to get"
        default: ""

    # Create Operation
    create:
        required: false
        description: "Create Application"
        default: "false"

    create_environment_id:
        required: false
        description: "ID of the environment to create the application in"
        default: ""

    create_credential_id:
        required: false
        description: "ID of the credential to use for the application"
        default: ""

    create_name:
        required: false
        description: "Name of the application to create"
        default: ""

    create_programming_language:
        required: false
        description: "Programming Language of the application to create"
        default: ""

    create_engine_version:
        required: false
        description: "Engine Version of the application to create"
        default: ""

    create_framework:
        required: false
        description: "Framework of the application to create"
        default: ""

    create_repository:
        required: false
        description: "Repository of the application to create"
        default: ""

    create_default_branch:
        required: false
        description: "Default Branch of the application to create"
        default: ""

    # Delete Operation
    delete:
        required: false
        description: "Delete Application"
        default: "false"

    delete_application_id:
        required: false
        description: "ID of the application to delete"
        default: ""

outputs:
    list_response:
        description: "Response from the List Applications Operation"
        value: ${{ steps.handler.outputs.list_response }}

    get_response:
        description: "Response from the Get Application Operation"
        value: ${{ steps.handler.outputs.get_response }}

    create_response:
        description: "Response from the Create Application Operation"
        value: ${{ steps.handler.outputs.create_response }}

runs:
    using: composite
    steps:
        - name: Run the Handler
          id: handler
          shell: bash
          run: bash "$GITHUB_ACTION_PATH/step-1.sh"
          env:
              R_HOST: ${{ inputs.host }}
              R_TOKEN: ${{ inputs.token }}

              # List Operation
              R_LIST: ${{ inputs.list }}
              R_LIST_ENVIRONMENT_ID: ${{ inputs.list_environment_id }}

              # Get Operation
              R_GET: ${{ inputs.get }}
              R_GET_APPLICATION_ID: ${{ inputs.get_application_id }}

              # Create Operation
              R_CREATE: ${{ inputs.create }}
              R_CREATE_ENVIRONMENT_ID: ${{ inputs.create_environment_id }}
              R_CREATE_CREDENTIAL_ID: ${{ inputs.create_credential_id }}
              R_CREATE_NAME: ${{ inputs.create_name }}
              R_CREATE_PROGRAMMING_LANGUAGE: ${{ inputs.create_programming_language }}
              R_CREATE_ENGINE_VERSION: ${{ inputs.create_engine_version }}
              R_CREATE_FRAMEWORK: ${{ inputs.create_framework }}
              R_CREATE_REPOSITORY: ${{ inputs.create_repository }}
              R_CREATE_DEFAULT_BRANCH: ${{ inputs.create_default_branch }}

              # Delete Operation
              R_DELETE: ${{ inputs.delete }}
              R_DELETE_APPLICATION_ID: ${{ inputs.delete_application_id }}
