name: CI - Preview Application

on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - closed

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    preview-application:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Preview Application
              uses: ./.github/actions/pr-preview
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  database_path: database.json
