name: CI - Preview Application

on:
    push:
    pull_request:
        types:
            - opened
            - reopened

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    login:
        uses: ./.github/workflows/devopness-login.yml
        secrets: inherit
        # Required Secrets:
        # - DEVOPNESS_EMAIL
        # - DEVOPNESS_PASSWORD
        with:
            host: ${{ vars.DEVOPNESS_HOST }}

    create-application:
        needs: login
        uses: ./.github/workflows/devopness-request.yml
        with:
            host: ${{ vars.DEVOPNESS_HOST }}
            path: "/environments/${{vars.DEVOPNESS_ENVIRONMENT_ID}}/applications"
            method: POST
            token: ${{ needs.login.outputs.token }}
            data: |
                {
                  \"name\": \"pr-${{ github.event.pull_request.number }}-preview\",
                  \"credential_id\": ${{ vars.DEVOPNESS_CREDENTIAL_ID }},
                  \"repository\": \"Diegiwg/devopness-tests\",
                  \"programming_language\": \"html\",
                  \"engine_version\": \"none\",
                  \"framework\": \"none\",
                  \"default_branch\": \"${{ github.event.pull_request.head.ref }}\"
                }
