name: Devopness - Login
on:
    workflow_call:
        inputs:
            host:
                type: string
                required: true
                description: "Host to send the request to"
        outputs:
            token:
                value: ${{ jobs.perform-login.outputs.auth-token }}
                description: "Token to use in other workflows"

jobs:
    perform-login:
        runs-on: ubuntu-latest
        outputs:
            auth-token: ${{ steps.extract-token.outputs.token }}
        steps:
            - name: Send login request
              id: login
              run: |
                  set -euo pipefail  # Enable strict error checking

                  response_file=$(mktemp)
                  trap 'rm -f "$response_file"' EXIT  # Cleanup temp file

                  status_code=$(curl -s -o "$response_file" -w "%{http_code}" \
                      --max-time 30 \
                      -X POST \
                      -H "Content-Type: application/json" \
                      -d "{\"email\": \"${{ secrets.DEVOPNESS_EMAIL }}\", \"password\": \"${{ secrets.DEVOPNESS_PASSWORD }}\"}" \
                      "https://${{ inputs.host }}/users/login")

                  # Check for HTTP success status
                  if [ "$status_code" -lt 200 ] || [ "$status_code" -gt 299 ]; then
                      echo "::error::Authentication failed with status $status_code"
                      # Try to extract error message from JSON response
                      if jq -e . "$response_file" >/dev/null 2>&1; then
                          jq -r '.message // "Unknown error"' "$response_file" | sed 's/^/::error::/'
                      else
                          echo "::error::Non-JSON response:"
                          cat "$response_file"
                      fi
                      exit 1
                  fi

                  # Validate JSON structure
                  if ! jq -e . "$response_file" >/dev/null 2>&1; then
                      echo "::error::Invalid JSON response from server"
                      cat "$response_file"
                      exit 1
                  fi

                  # Preserve response for next steps
                  cp "$response_file" response.json

            - name: Validate and extract token
              id: extract-token
              run: |
                  set -euo pipefail  # Enable strict error checking

                  # Validate required fields
                  token_type=$(jq -r '.token_type // empty' response.json)
                  access_token=$(jq -r '.access_token // empty' response.json)

                  if [ -z "$access_token" ] || [ -z "$token_type" ]; then
                      echo "::error::Invalid token response structure"
                      jq . response.json
                      exit 1
                  fi

                  # Mask tokens in logs
                  echo "::add-mask::$access_token"

                  # Set output
                  echo "token=$access_token" >> $GITHUB_OUTPUT

                  # Optional debug information
                  expires_in=$(jq -r '.expires_in // "unknown"' response.json)
                  echo "::debug::Token type: $token_type"
                  echo "::debug::Token expires in: ${expires_in}s"
