name: Test

on:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login on Devopness
              id: devopness-login
              uses: ./.github/actions/devopness-login
              with:
                  host: ${{ vars.DEVOPNESS_HOST }}
                  email: ${{ secrets.DEVOPNESS_EMAIL }}
                  password: ${{ secrets.DEVOPNESS_PASSWORD }}

            - name: Get projects
              id: projects
              uses: ./.github/actions/devopness-request
              with:
                  host: ${{ vars.DEVOPNESS_HOST }}
                  path: "/projects"
                  method: GET
                  token: ${{ steps.devopness-login.outputs.devopness_token }}

            - name: Show projects
              run: echo '${{ steps.projects.outputs.response }}' | jq
