name: Test

on:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    login:
        uses: ./.github/workflows/devopness-login.yml
        secrets: inherit
        # Required Secrets:
        # - DEVOPNESS_EMAIL
        # - DEVOPNESS_PASSWORD
        # - DEVOPNESS_HOST

    get-projects:
        needs: login
        uses: ./.github/workflows/devopness-request.yml
        secrets: inherit
        # Required Secrets:
        # - DEVOPNESS_EMAIL
        # - DEVOPNESS_PASSWORD
        # - DEVOPNESS_HOST
        with:
            path: "/projects"
            method: GET
            token: ${{ needs.login.outputs.token }}

    debug:
        needs: get-projects
        runs-on: ubuntu-latest
        steps:
            - name: Debug
              run: |
                  echo "Projects: ${{ needs.get-projects.outputs.response }}"
