name: Test

on:
    push:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    login:
        uses: ./.github/workflows/devopness-login.yml
        secrets: inherit
        # Required Secrets:
        # - DEVOPNESS_EMAIL
        # - DEVOPNESS_PASSWORD
        with:
            host: ${{ vars.DEVOPNESS_HOST }}

    get-projects:
        needs: login
        uses: ./.github/workflows/devopness-request.yml
        with:
            host: ${{ vars.DEVOPNESS_HOST }}
            path: "/projects"
            method: GET
            token: ${{ needs.login.outputs.token }}
