name: Test

on:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login on Devopness
              id: devopness-login
              uses: ./.github/actions/devopness-login
              with:
                  host: ${{ vars.DEVOPNESS_HOST }}
                  email: ${{ secrets.DEVOPNESS_EMAIL }}
                  password: ${{ secrets.DEVOPNESS_PASSWORD }}

            - name: Create Application
              uses: ./.github/actions/devopness-application
              with:
                  host: ${{ vars.DEVOPNESS_HOST }}
                  token: ${{ steps.devopness-login.outputs.devopness_token }}

                  create: true
                  create_environment_id: ${{ vars.DEVOPNESS_ENVIRONMENT_ID }}
                  create_credential_id: ${{ vars.DEVOPNESS_CREDENTIAL_ID }}
                  create_name: test-app
                  create_programming_language: python
                  create_engine_version: 3.12
                  create_framework: none
                  create_repository: Diegiwg/devopness-tests
                  create_default_branch: main

            - name: Get Applications
              id: get-applications
              uses: ./.github/actions/devopness-application
              with:
                  host: ${{ vars.DEVOPNESS_HOST }}
                  token: ${{ steps.devopness-login.outputs.devopness_token }}

                  list: true
                  list_environment_id: ${{ vars.DEVOPNESS_ENVIRONMENT_ID }}

            - name: Show applications
              id: application
              run: |
                  echo '${{ steps.get-applications.outputs.list_response }}' | jq

                  # Save the First Application ID
                  APPLICATION_ID=$(echo '${{ steps.get-applications.outputs.list_response }}' | jq -r '.[0].id')
                  echo "APPLICATION_ID=$APPLICATION_ID" >> $GITHUB_OUTPUT

            - name: Get Application
              id: get-application
              uses: ./.github/actions/devopness-application
              with:
                  host: ${{ vars.DEVOPNESS_HOST }}
                  token: ${{ steps.devopness-login.outputs.devopness_token }}

                  get: true
                  get_application_id: ${{ steps.application.outputs.APPLICATION_ID }}

            - name: Show application
              run: |
                  echo '${{ steps.get-application.outputs.get_response }}' | jq

            - name: Delete Application
              uses: ./.github/actions/devopness-application
              with:
                  host: ${{ vars.DEVOPNESS_HOST }}
                  token: ${{ steps.devopness-login.outputs.devopness_token }}

                  delete: true
                  delete_application_id: ${{ steps.application.outputs.APPLICATION_ID }}
