name: Test

on:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    login:
        uses: ./.github/workflows/devopness-login.yml
        with:
            email: ${{ vars.DEVOPNESS_EMAIL }}
            password: ${{ vars.DEVOPNESS_PASSWORD }}
            host: ${{ vars.DEVOPNESS_HOST }}

    debug:
        needs: login
        runs-on: ubuntu-latest
        steps:
            - name: Debug
              run: |
                  echo "Token: ${{ needs.login.outputs.token }}"
